---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wasm-enabler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k0s-app: wasm-enabler
  template:
    metadata:
      labels:
        k0s-app: wasm-enabler
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: plugin.k0sproject.io/wasm-enabled
                    operator: DoesNotExist
      initContainers:
        - name: wasm-enabler
          image: quay.io/k0sproject/k0s-wasm-plugin:main
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
            - name: bin
              mountPath: /var/lib/k0s/bin
            - name: imports
              mountPath: /etc/k0s/containerd.d/
      containers:
        - name: dummy
          image: registry.k8s.io/pause:3.6
      volumes:
        - name: bin
          hostPath:
            path: /var/lib/k0s/bin
            type: Directory
        - name: imports
          hostPath:
            path: /etc/k0s/containerd.d/
            type: Directory
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmtime-spin
handler: spin
