cluster_name: raccoon
domain: lab.shortrib.net
cluster_image_name: ubuntu-24.04-server-cloudimg-amd64.img
default_password: ENC[AES256_GCM,data:k+T2sO3lslQWLJbQGE3vn4KWXLTbzJDX9A==,iv:ehBGWjX2+TpusfdAlhoR4jENlQ7Wvg95mpnBUkWhx2s=,tag:Q2O9TeDkh+9MDu+5YFuyLw==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 52:54:00:18:06:0a
    control_plane_cidr: 10.24.6.0
    load_balancer_cidr: 10.23.6.0/24
node:
    cpus: 3
    memory: 6144
    disk_size: 80
nutanix:
    prism_central: prism.lab.shortrib.net
    username: admin
    password: ENC[AES256_GCM,data:T6FdD5jH6HRYdyxZ2FXD6LgU1DQA1XyEHMyoLAAW,iv:YZUEV+J4PMzHmPv6m+++Umod3Oi6+AncdXyQ7oEnFmQ=,tag:u8oIzLVGINdc/SVOAEWTXA==,type:str]
    datacenter: garage
    cluster: homelab
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
tailscale:
    client_id: kjsLGj1UgG11CNTRL
    client_secret: ENC[AES256_GCM,data:OMa+4M5xacbAnOiEv+0DiDugrCX2Sbo9k7Rbd2RJTMAupFcnaMdOb5UcRpcbEFcpXDg8Nc35/8SQPCI9laerLw==,iv:t31xtzYp+9/ZltFf7yf1Ag/7LbliSxYsZvZzDMR+dWI=,tag:U+x0zZoc4OtO92X5FcGPqg==,type:str]
sops:
    lastmodified: "2026-01-01T17:42:50Z"
    mac: ENC[AES256_GCM,data:VMJO0677sx7RiCllLM+rTnzk1EWPwhesNXaH8sQPq7uf9O4LSPQRZtp3CcPRl1aOTwoxcK1Q4OE7wQW1kAf8E3GEobrBcsDml03Do+fGedZZoR1hJG+fpewnTe0jZdSKnpwZZzOb+VNPRwQoPT7NFCbltACpg46EO2RuW+Dpbrs=,iv:qoSpa54S89ZBo5BsRs+4tvbzEjxJ8kMRJAG5LHDLsDA=,tag:ahjGmF5kKXfAk5J14FN0XQ==,type:str]
    pgp:
        - created_at: "2026-01-01T17:42:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAOe72aFe7i/A+geHPvolSe2oiGeV9Th9p7hLy6t2Smy4w
            jPUxr2OedGt/GqUMqPYeskZYTMlKRV/CmL5o7BQbQnuVsqO3tF/2hEUZdD8yzSXm
            0l4BgUGeJ0FGICS/dp45P0Cw0DXAxStwRdUM4g0dqkFBe/oRf+mYf0HKIxBvZ9fE
            EScf92Cku0Xxbc1jLD6btLDaQVAkP9u0DvXeFvsq7+R+YK3LtlMn2h8iQscO5iEC
            =6KGE
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
