cluster_name: vole
domain: lab.shortrib.net
cluster_image_name: ubuntu-24.04-server-cloudimg-amd64.img
default_password: ENC[AES256_GCM,data:ljxqQHckpFVl8MQOGlqW3n/yqxeIZbLpCA==,iv:tbewnXC0FcR7BSRAJ01yl/jhH052FWm9+ZwbVyTd2cM=,tag:fxN/rpkjTX6kj+cd+BCkXA==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 52:54:00:18:09:0a
    control_plane_cidr: 10.24.9.0
    load_balancer_cidr: 10.23.9.0/24
node:
    cpus: 3
    memory: 6144
    disk_size: 80
nutanix:
    prism_central: prism.lab.shortrib.net
    username: admin
    password: ENC[AES256_GCM,data:PAewyL7CseHgR4r0MhBz/EVe4xYUgvC8P+39PA==,iv:+3v3T+yzq3Xm8aE6i3AlyH9rfUCczKISFMjOH/NsxUs=,tag:qZ6Ju9PwHQMrqxrUnf65FQ==,type:str]
    cluster: homelab
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
tailscale:
    client_id: kdynYU1Uw521CNTRL
    client_secret: ENC[AES256_GCM,data:Gy2UP04XV2neREy0nPiz7P7tv1mmB7Qkg2GyV5f+oZCLGVfMPh6FANSy15NnB3P7cG/S0XhgH53jTDe53k3D,iv:+5RNpoOijDyMHlybRCaCzYzVypsdDf1xlvFWbHTbgvw=,tag:iVTZen61dBOoKbUQpmrzyA==,type:str]
sops:
    lastmodified: "2026-03-30T16:10:44Z"
    mac: ENC[AES256_GCM,data:gd4ibP1R+EXIqlrNNpmFUgeFz0zSyhKDlR+Qg0Y+o5l2Q/V5gZ4JDrNO7Rn6ZS3fdemq+WJgy1DO9N/uOlKKsZVxp4XSCcdDkGhPCqkKxX78OSdG1/Gr4xbybIvw8YNUZNVJCHVugcf0xUzpE3E0AoAu8pdl6Tx0HUjS9+LBGBI=,iv:MNQGCBoTcWy9g2ZyiDXpHvP9LqokT1eFw8O0thSDdAQ=,tag:l1W8zBpuQJv5mwSHS+6kpQ==,type:str]
    pgp:
        - created_at: "2026-03-30T16:10:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAN17quiOqMUbQVcTgpHse0VcBxvH4TS3by1MY9ZhGvgkw
            EI8XtZInWzkMHPydyLxM7Qu824dqau3m1r6+kgfZ83P3aZUk1T0BMklMnTCrOH3K
            0l4B7h0TNmP+ypEPncRFhmQZWK0OHXmFJu0Vxjvxo4XdB+nWgoNfGpowdzIGp6zv
            QcMrbkyF+oubuutyZHSuKJw9P+gs96+wpyZJa5hfhFNiDYGVhJxW8I3L6Aelhkbx
            =fLpL
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
