cluster_name: opossum
domain: lab.shortrib.net
cluster_image_name: noble-server-cloudimg-amd64.img
default_password: ENC[AES256_GCM,data:QoQiYeYQr6Rv7mVM/CJjCA2tI6iNWuCI/A==,iv:LYodf0CPNMUNjA0bwcN789YwG5S3QmUkNwyDJoYX1hU=,tag:x55OFNhU8HSk5blIH+zmMQ==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 00:50:56:18:01:0A
    control_plane_cidr: 10.24.1.0
    load_balancer_cidr: 10.23.1.0/24
node:
    cpus: 3
    memory: 6144
    disk_size: 80
nutanix:
    prism_central: prism.lab.shortrib.net
    username: admin
    password: ENC[AES256_GCM,data:UQSZGUAAQlLNKt+6qogJV9NqWg==,iv:hWz6hOQicIaDT8yJErI8dmNXn85G7Cf84Eyvu91mC98=,tag:p1t9FJwrsIR2B6H3sNtyqw==,type:str]
    cluster: homelab
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
tailscale:
    client_id: kx7Kmd86kN11CNTRL
    client_secret: ENC[AES256_GCM,data:xmxQDxSJtV8RQR2+fLEPni3FYGN2oM6vFlqPP7lpN1+F6yUOSKvVmYAWW8isHoFa9U80dbBD5CFQJF7hE30UnA==,iv:PXXPTmE+4zX/gDFw1ieCkOGGLERDSU8tyJj2b8yOybQ=,tag:3blnKGUqZ4ds78/Z1xENxw==,type:str]
sops:
    lastmodified: "2025-12-10T05:38:45Z"
    mac: ENC[AES256_GCM,data:arHi6KoUl6fY96pbxZktto9H31lNrRyONED2EJKPjSX0y/DqJDv7NinEsmO5EOGWuVspvGROSjSfEqGTxVfGcBaXr7uSnZiI9xFlfRidBiVyNKRTvLq7q2VwBI1RWkSlTpB03csOKIsQtPemKlC3AZUQkrKY03QEBwHjuVR9xzo=,iv:csrr/YGbT0/kpnpCu1/j91VIJ67RiGXAh4er/htyYUE=,tag:nWGaTTRVCUMypMdEoFqLBg==,type:str]
    pgp:
        - created_at: "2025-12-10T05:38:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAm0ymsQd26rd3fpRzNhVGjwn7Duqa7lIDoQeoNHeN0ggw
            ohn0ajCr0j0pRwGU3TKIgodF+C1IUc3LG2oKSR5qwjy3nofsV5AcbMEjoa3au5ma
            0lwBRafEAca1D0if9P0WoVfaw09W3RYeCG0tSxZjYhx6pH9VGSh2oOcIwJCLR0Pb
            soZKzkkwRTpuJOWWx60LGAoEEQnqyClIOB0qkRlxBGybelXtQd/WzzX1F0gE5w==
            =L9z5
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
