cluster_name: gerbil
domain: lab.shortrib.net
cluster_image_name: ubuntu-25.04-server-cloudimg-amd64.img
default_password: ENC[AES256_GCM,data:1Ow6UpmdXs6COSYwaIpAjBxByFygL++oYw==,iv:GS4pAIx+76t7TwOk/CtIQ7xMSQyw4Vlq1ybFnBVEsFI=,tag:Psl1m7GW8CdPIBLDS/iSjQ==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 3
    control_plane_mac:
        - 52:54:00:18:0b:0a
    control_plane_cidr: 10.24.11.0
    load_balancer_cidr: 10.23.11.0/24
    runtimes:
        gvisor:
            enabled: true
node:
    cpus: 4
    memory: 8192
    disk_size: 80
nutanix:
    prism_central: prism.lab.shortrib.net
    username: admin
    password: ENC[AES256_GCM,data:e8150V3ixU6Zt+oG0fHgRbDmo3USf+LnfMC0,iv:7QGIO11BFc6PkBOXgwDUDvkcd6Y3e6KHez4MxAsr2Lw=,tag:TksRPiJHysNB8fmucu2Twg==,type:str]
    cluster: homelab
    storage_container: kubernetes
    file_server: rickhouse
    subnets:
        kubernetes: kubernetes
        workload: workload
    files:
        server: rickhouse
        fqdn: rickhouse.shortrib.run
        username: gerbil
        password: ENC[AES256_GCM,data:iAAD7jIw8gDy7yE9OHpNf1Ef/AlUnw==,iv:wMNdrIaSSnD/Udnx8+p/L9+xld9XawLjN30wgI6PZOU=,tag:M48KZ3/91oMm7oFbzwB+cg==,type:str]
tailscale:
    client_id: kKb5wyRNek11CNTRL
    client_secret: ENC[AES256_GCM,data:YZnH7KhxVaEcB/7EGBKKmohBXclb9dC9nFpf855tAGRcaEQ3OzYxNHwQUi4sq0PU+qPydwXcqazVYpVcbvuw,iv:0hgEr8SDL74vFDkfwMOaNA/NuCwqBvTMKjxfU+IN0h4=,tag:GgwGvWM6ODCqSGKC2ngpBw==,type:str]
sops:
    lastmodified: "2026-04-16T10:28:56Z"
    mac: ENC[AES256_GCM,data:pi8QMFg+3Oe0t54jayBtPKq/+on4XnBMLFjj6IeRB4bYQ1RI/Dx8Cs7aBML3TSMsEvMWUilA4g8cFI0Ntgq1mPQFJ4S/Vcp6VquREhsQfo5R0e2DwcRzmSxCwSb6m41MJ67rLYPxKKSBdxGXouH8t9p3GOvrTkdUNa/deorq8Us=,iv:SDSwgiTBGBHYuLHmqJPgGtExvFguTw9qEPXUO0pH1xc=,tag:r4AFuD9aEFN/eJrhdwFkCA==,type:str]
    pgp:
        - created_at: "2026-04-16T10:28:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdA+1KXBPS13OpeXtJaAZx30KTedJbWXgTbooVdVMO5xw4w
            4Dzuzc8z1SFt5+jxynbBmBh2tzpmgaSUnzpAKSizfc0WEwfn6WDnJT6C7DGwrftC
            0l4BlzKm14KfAnmlw8p7P8VwEk37iydFsnm99PlDpRbPW1CDp8f+70vk7FNTaYfl
            4tQwGjw8AiMgJiZ4UpfwIi8IiN+3akKBx5lm2sMMjKz9DEm3UQ1S/bNAHcKp83fl
            =fPuj
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(.*password|api-key|client_secret)$
    version: 3.11.0
