cluster_name: opossum
domain: lab.shortrib.net
remote_ovf_url: https://cloud-images.ubuntu.com/plucky/current/plucky-server-cloudimg-amd64.ova
default_password: ENC[AES256_GCM,data:lIstIgxRFlGse8dkpoxDc7UZ1SSb6mrZbQ==,iv:VAgDoheNpEQH5QZciK0zKgLwb/IIDxPDpJBElzlyRxo=,tag:T3k2GcRY9BZNKCDsyyERBA==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 00:50:56:18:01:0A
    control_plane_cidr: 10.24.1.0
    load_balancer_cidr: 10.23.1.0/24
node:
    cpus: 3
    memory: 4096
    disk_size: 40
vsphere:
    server: vcenter.lab.shortrib.net
    username: terraform@shortrib.local
    password: ENC[AES256_GCM,data:XLszyw+jxUvlGAGgEnIPyH9VMw==,iv:eR9m9l3J9LJmFrpWJSF6H9EbAeeGlF8HXlhICYzzqdg=,tag:cHMsBCthYBZuC3y6coO2nA==,type:str]
    datacenter: garage
    cluster: homelab
    host: rye.lab.shortrib.net
    resource_pool: homelab/Resources/clusters
    kubernetes_network: kubernetes-pg
    workload_network: workload-pg
    datastore: vsanDatastore
    folder: clusters
cloudflare:
    api-key: ENC[AES256_GCM,data:hBnFHrJzkadOXCEioWShdbe/+BHo8eSA4fNnIPZBOyo7eso40A==,iv:jB3PiHAx+1OfTogqNB8aT6uaUG1yuxKPxcGejNeDUOI=,tag:v95zhM4lRmFRg4csCshe9Q==,type:str]
tailscale:
    client_id: kZzRH1J7hX11CNTRL
    client_secret: ENC[AES256_GCM,data:6T1pARbEiW9AdXtD8H4FK1R32XO7umU5RYNDoCep/ipsyJkHYirwDC5ZKT9NBt0e4+j0ATo5bAG9jBZs+qNs,iv:iOFJCX2loXTJBDdSYoCwprLY8AsxwhQ5DzWLO70xpuY=,tag:f7cwaeLn7cYOCpLm2FDwBA==,type:str]
sops:
    lastmodified: "2026-04-13T18:16:32Z"
    mac: ENC[AES256_GCM,data:IqLzmetoRRoISBQWffPf5pvp0G8687VFLCD5QYqb/tMIwgRXGdxjtGNeaGD4XAu+Zek3gHfLqv4SOI6soUInf5dVcbFqiwMyDormxmuX1QHv40IPEjv+DCfLo1xomMl7IJueaT5l+E2QmRN6GNy2DWyybaFO2W/DXlPar1JGp7g=,iv:KgaMtT5CNG0BPasChtoStGfFI0wucZtIvVJE19LDG7Y=,tag:R2kpeIqiB1+94q2Tn7qPvQ==,type:str]
    pgp:
        - created_at: "2026-04-13T18:16:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAn23WeUrIIKJV90hT6XyLAcMolhSv0o/VVxN211+NtDgw
            5fwUbXG5RaHBINlic4PFz3FX6KMrsKSbRP7VxoagfBjUivL5lGie337RN6UWt6lx
            0l4BCMQFY3Q3Y+6KGAITWUBFt8xWHJmGh04PcLPdS5qUbN/sw2t2pC0u2U81bKF0
            dETv4JQEG3s7jlAdu5lpnHUwwj5nWhX8sz2iXt8tvmUY8jWiXrdSS2x+tLv8bBSH
            =Q10G
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
