cluster_name: vole
domain: lab.shortrib.net
cluster_image_name: ubuntu-24.04-server-cloudimg-amd64.img
default_password: ENC[AES256_GCM,data:Awgq/A3SRRdLY9wPaRPMvekT3n7smIyGmw==,iv:HEjxHqKw6eVh0PRjp0KEPMuiAT+99ebDlnYec+J8lMQ=,tag:HgKilOPCVPJSyAEEMznPTw==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 52:54:00:18:09:0a
    control_plane_cidr: 10.24.9.0
    load_balancer_cidr: 10.23.9.0/24
node:
    cpus: 3
    memory: 6144
    disk_size: 80
nutanix:
    prism_central: prism.lab.shortrib.net
    username: admin
    password: ENC[AES256_GCM,data:X4iGVJhN5RsFUHrc6Fgfo1btvfyhNMCAvOKFPZ+z,iv:cyEVd8WbflU84CUh2ea2IvGdNl4OgCcBiXyDCHpOLuk=,tag:9UnOhkVQqcv3O4Z2IS02uw==,type:str]
    cluster: homelab
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
tailscale:
    client_id: kdynYU1Uw521CNTRL
    client_secret: ENC[AES256_GCM,data:oCehfi6yclFBx6tAJnmtA6vMsqZ9HTspz34Y3Vxn2qYYF3n3q7MIa1DFck0iPqTNd/fW5f4X8Y2hm5bCJ+ys,iv:0GjSWyPspmGVIESkkzbVGcgjDUZuGgOlw18ZgnOVQWU=,tag:ecpPa1L6sLOiwpSowmzSBA==,type:str]
sops:
    lastmodified: "2026-01-01T15:54:45Z"
    mac: ENC[AES256_GCM,data:qYkC2Od1wV3qDAU/o74Sw4cRwPviGrzURTZBnw+G1bqrUc7eJkf0IzkSYhVENTs/agHIZX+RfxK8EOe9+oKeiAVitOWXJt6Px0CIF6psIdAOmOu44x75bfh9Dd8cQjGOKedmdNPnMnKqRna+PGaE8OoN8VahutB5kGnwJepmqc0=,iv:ilU1iv2YifdifUw4bHtyEXR3fTTJD1XxUWDNBojNMRY=,tag:pA04UCA0uQ2fCrXR5DLURg==,type:str]
    pgp:
        - created_at: "2026-01-01T15:09:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAl95H9xRwG2zmlPwHvUTU4hDT1HNgnImGjBmMdYd/5GYw
            wwkvUoqi510r/5KzuYYFZkgCqEL0ZAfn5LvJ7Bk7mRa2P9hfbwMjn19C0KoebcJj
            0l4BOQZxMxILUIlXIosmT+SOv49KRoqdWbpfh3Ilq+XYCwiHwUwa6IgaTqvD/zVP
            tmlCDmmDEBrFwiMtJqGGBcoayGl9uA+95zcvJ+VZgvqcC+Okk5nMEmPMqlZsgZ1F
            =KiFR
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
