cluster_name: nutria
domain: lab.shortrib.net
remote_ovf_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.ova
default_password: ENC[AES256_GCM,data:J7CwEwI6VAu/kdESOJ0wcturasHbTVcCzA==,iv:xyaR3nbyhZHMOkdLqWyAh2W11Rr0Qct8AJDCDVVWYvk=,tag:oo4q3kvvwXp5PDLnmhfBuw==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 00:50:56:18:04:0A
    control_plane_cidr: 10.24.4.0
    load_balancer_cidr: 10.26.4.0/24
node:
    cpus: 3
    memory: 4096
    disk_size: 40
vsphere:
    server: vcenter.lab.shortrib.net
    username: terraform@shortrib.local
    password: ENC[AES256_GCM,data:ohPua6ET5WpCMkpq/oYLNVJcjxw=,iv:CA8LmBJOr/AEjr4sNx8yFu5yUTaeFfOEoeuMjy1eMqI=,tag:ooph33Jy5die5Y6OASyO0g==,type:str]
    datacenter: garage
    cluster: homelab
    host: rye.lab.shortrib.net
    resource_pool: homelab/Resources/clusters
    kubernetes_network: kubernetes-pg
    workload_network: workload-pg
    datastore: vsanDatastore
    folder: clusters
cloudflare:
    api-key: ENC[AES256_GCM,data:ruYdqOc4fjM/lUV4vFTKNiTfkykfjLhMo4os0qLmxogPF7gydw==,iv:4Ix1lfN6EVAUntBC8NOlAzfywUDKqMjY5KvWDkk0nxM=,tag:+E4oe8XQPqiOPQP7YQysIA==,type:str]
tailscale:
    tailnet: crdant.io
    api-key: ENC[AES256_GCM,data:OHUJrFkLTmxfBEZS8pKiWBIXRgvJwRUJhPoGtzzyu8qO548k7MxWBv/c61sKfjW5d6yz1mT/Sg==,iv:A/bDNM4t2cIV0SOYRkURy1r/a6ckbhLG0K6l3TfUW/8=,tag:MWFFakzSxN/7R9woKYkVLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-03T21:00:42Z"
    mac: ENC[AES256_GCM,data:mNEYFdytq8sZ1+50zravnNffWpgwFQSO1h605axjoeE9BUN/YrCVWoD456h4rgPqKCb75pVh4IZgO+J9fmR6KWJn79Oj8Ixs+f10XTa641XPRPgPvprOUTiTTKVZdjUo6fjJlE0BV/mL6NM+QlxNEE1fCo6Vb7SDe7iuRi8/pXQ=,iv:6Aq2Cxconop0TsNvDRquZEu0peCoXI5Lq4U5HCgMb0I=,tag:mVrL0214NoazGhuHWcXluQ==,type:str]
    pgp:
        - created_at: "2023-07-12T03:38:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAd+k72h1mVci/fHyBGfMmH+5aEHT8Ji6/PWkxBZ+ic3Iw
            qjOkev3WEkEL1/G/2BA5cTx9eL3BoBTqXk/LSqHEd/uCAAr5Afi+kPCUMrIFIbL3
            1GgBCQIQ4sdqcbewDEu8BA7X+AbwidOrwF+2qxBAqMPAS2FdxIUrLpLAW+f0jUc4
            FZ9hnQD/M+GVRLA1/w+tSy7WXYTo7ePOiLM7cRsD6ZE0k+zWTf7TN/JHQ7Kqm7RD
            oJx4wxsLmE45yg==
            =3Sqn
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password)$
    version: 3.7.3
