cluster_name: muskrat
domain: lab.shortrib.net
cluster_image_name: noble-server-cloudimg-amd64.img
default_password: ENC[AES256_GCM,data:BqJcNyFhWKa8aNB93fLeiE/5onDoFvruAA==,iv:bgn1nYvmJVzHAdi4hvml18CFuu9znvW4hFGKfpn/vRc=,tag:vWo+n9S+OyAYyH9ORPN2Ww==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 5
    control_plane_mac:
        - 52:54:00:18:02:0a
    control_plane_cidr: 10.24.2.0
    load_balancer_cidr: 10.23.2.0/24
node:
    cpus: 8
    memory: 16384
    disk_size: 150
nutanix:
    # Prism Central IP or FQDN
    prism_central: prism.lab.shortrib.net
    # Prism Central username
    username: admin
    password: ENC[AES256_GCM,data:HMW1m6p44zw6JHCxEUKbp7l9HQ==,iv:MuSmqdg/7XZ3gwWFV2DIXziwbTsjrL9fv1hO/qMGGiw=,tag:8JHJBLWeyRaduo5uHSbTyQ==,type:str]
    # Nutanix cluster name
    cluster: homelab
    # Storage container for VMs
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
tailscale:
    client_id: kZzRH1J7hX11CNTRL
    client_secret: tskey-client-kZzRH1J7hX11CNTRL-JwRwVA8LUF3aDv8AcpwML31JirayzUqZ
sops:
    lastmodified: "2025-12-10T04:53:42Z"
    mac: ENC[AES256_GCM,data:yP65QYVOurDFzaSkVamPXfzTPijvwwHyWIkeSAhrDpFuHzUp3Q1CdiYEbeCnfsb4iUxLH8/WQX8IO6UOzyQtnZfkodNfZ0kwn55j2IaJTJQ4D7TwZM8IpnOg/vgMD6wllCaPA7lCUQ7eCSWjviwMYYKAO6c25dvkOvh7+o3pBJs=,iv:bUO3AECs9R9dt+fJHIvD+W6B0+rkF9QfGJc2/Q9/QKE=,tag:VXToEt32kTBh3FwKAb3BOA==,type:str]
    pgp:
        - created_at: "2025-12-10T04:37:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAnWaV4Rl1GgQp+oeQdFQ2WB4v9gqPoIdAVNhknH14h24w
            EQh+c10zXv8GRXGqVuGR6HYEtEa8JnKUiZl83ytMUMCzdwRTz81HCDqufNtYfaBy
            0l4Bx1Db3/GujIna/08hiuRHlTsqEkoKmGEFeo+6RxkBHrxU3V6QT0D8ltSMXShi
            6r2266v/JdVGI5ZtxpzpJXIMP81t3BlfNizUU2cQVd/UF5q/7+eZrGHgXNOk+gkB
            =b+Ru
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password)$
    version: 3.11.0
