cluster_name: raccoon
domain: lab.shortrib.net
cluster_image_name: ubuntu-24.04-server-cloudimg-amd64.img
default_password: stole-unroll-unused-squad
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 52:54:00:18:06:0a
    control_plane_cidr: 10.24.6.0
    load_balancer_cidr: 10.23.6.0/24
node:
    cpus: 3
    memory: 6144
    disk_size: 80
nutanix:
    prism_central: prism.lab.shortrib.net
    username: admin
    password: nursing-kn1TTing-nirV@Na-faces
    cluster: homelab
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
tailscale:
    client_id: kjsLGj1UgG11CNTRL
    client_secret: tskey-client-kjsLGj1UgG11CNTRL-NGqmDCHDjaWGHaPC2uYqVWJRNwZtyrR9g
