cluster_name: node
domain: lab.shortrib.net
remote_ovf_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.ova
default_password: ENC[AES256_GCM,data:J7CwEwI6VAu/kdESOJ0wcturasHbTVcCzA==,iv:xyaR3nbyhZHMOkdLqWyAh2W11Rr0Qct8AJDCDVVWYvk=,tag:oo4q3kvvwXp5PDLnmhfBuw==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:17 600 602
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 3
    ip_pool: 10.26.0.144/29
node:
    cpus: 3
    memory: 4096
    disk_size: 40
vsphere:
    server: vcenter.lab.shortrib.net
    username: terraform@shortrib.local
    password: ENC[AES256_GCM,data:zJr0EWVk3prVh2L9XsahKFOGDQ==,iv:f5WUqup49DclAWiWp0nU4LDXbLm9767eK5IGcT5RYrY=,tag:POIqX14NB5L+TnBstEgK8Q==,type:str]
    datacenter: garage
    cluster: homelab
    host: rye.lab.shortrib.net
    resource_pool: homelab/Resources/kurl
    kubernetes_network: kubernetes-pg
    workload_network: workload-pg
    datastore: vsanDatastore
    folder: replicated
cloudflare:
    api-key: ENC[AES256_GCM,data:ruYdqOc4fjM/lUV4vFTKNiTfkykfjLhMo4os0qLmxogPF7gydw==,iv:4Ix1lfN6EVAUntBC8NOlAzfywUDKqMjY5KvWDkk0nxM=,tag:+E4oe8XQPqiOPQP7YQysIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-12T03:38:24Z"
    mac: ENC[AES256_GCM,data:YM4WWfvBLswKfgwVx2crAVRLuhoJ05Q/8TnwU4ZNraobfy0zBsbceOf9ej3UJ4Zk1SiOogUHHpYLvrXh9p7+53/GDK5lCjF9pqF4t45ah6Ccnz1yRuQq1HG71R9c3xwhz/FT9iubiv9eJHulUfhcyrMkQWmdnmbcqoPu117o0O0=,iv:i5bQBsnpNdqksIS1pOrs2UD9ZsETAV4Ue43KTViEH/8=,tag:OkT0fj3lKz/k0fF4N673TQ==,type:str]
    pgp:
        - created_at: "2023-07-12T03:38:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAd+k72h1mVci/fHyBGfMmH+5aEHT8Ji6/PWkxBZ+ic3Iw
            qjOkev3WEkEL1/G/2BA5cTx9eL3BoBTqXk/LSqHEd/uCAAr5Afi+kPCUMrIFIbL3
            1GgBCQIQ4sdqcbewDEu8BA7X+AbwidOrwF+2qxBAqMPAS2FdxIUrLpLAW+f0jUc4
            FZ9hnQD/M+GVRLA1/w+tSy7WXYTo7ePOiLM7cRsD6ZE0k+zWTf7TN/JHQ7Kqm7RD
            oJx4wxsLmE45yg==
            =3Sqn
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password)$
    version: 3.7.3
