cluster_name: ferret
domain: lab.shortrib.net
cluster_image_name: ubuntu-24.04-server-cloudimg-amd64.img
default_password: ENC[AES256_GCM,data:n1As8xpEtyLBHH2BUCZWOnFN3Uts/yEvbg==,iv:L+KTO25WXaqfe+ZDDTCyw1OZGa8y4y61wrMJaWyWVFw=,tag:Vg3M+G0bMI69UW854MllFA==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:20_890_576
users:
    - default
    - name: crdant
      gecos: Chuck D'Antonio
      groups:
        - users
        - adm
        - sudo
        - ssher
      ssh_import_id:
        - gh:crdant
      sudo: ALL=(ALL) NOPASSWD:ALL
      lock_passwd: true
cluster:
    controllers: 1
    workers: 2
    control_plane_mac:
        - 52:54:00:18:03:0a
    control_plane_cidr: 10.24.3.0
    load_balancer_cidr: 10.23.3.0/24
node:
    cpus: 3
    memory: 6144
    disk_size: 80
nutanix:
    prism_central: prism.lab.shortrib.net
    username: admin
    password: ENC[AES256_GCM,data:SfLB05nW85OMuqV+6Ws4cFT2W6MD24lv765/KKi+,iv:MqGWyMR0Q0m+7Sk/pE+f8UDnVU6hpKAJhAi4KiEIyj4=,tag:iCIPKjWGCQFwHSuBFn9Fkg==,type:str]
    cluster: homelab
    storage_container: kubernetes
    subnets:
        # Management network subnet
        kubernetes: kubernetes
        # Workload network subnet
        workload: workload
tailscale:
    client_id: kx7Kmd86kN11CNTRL
    client_secret: ENC[AES256_GCM,data:12EtHVV2f2gSSSZLROOg4CrZ/3tNRrid0bOWSiaVJZAEqNBUEAr1xYwaENTCUj2UG7TBTqDSg1OD30J8KlDbbA==,iv:+k2s+6rs4w/giqurj0trjvxqKq9YT7ggAISttGHEtRU=,tag:PJdhO2rt8lIOJ28NVvJICQ==,type:str]
sops:
    lastmodified: "2026-01-01T15:55:18Z"
    mac: ENC[AES256_GCM,data:mSRpeiHvqaGTiXSvCctwCwrlczqJJdsxORdfBKjuQzOJhFCq28ZPD2HHZLfGzZRUtIzQQqP75b/elduuE1cZjTXlc2nAxNCEAJ4KK7Z1KF6X/md+R869FeTZyP9vReLcVuOYT9hiLSGQErkoMtUcY7/sN8wGJxoNvmys/tRLMbM=,iv:pvURpmDyXfDL/SMDvZ1G8Xqv2sqSnuxDvWpuzjO/PCg=,tag:v6Sz0vpd7XKZLTAuZ2aCwg==,type:str]
    pgp:
        - created_at: "2025-12-10T06:07:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAbiwjVj5vIuvOreTgSCKAFVpcvTqghKuPuXXpDFubZnQw
            BIM8mWSb9jMecsjUeYjM65soQu+lxfsr2HYWEHOdm4XmVF9e59KMAv6Ht8EVPK/r
            0l4BI8QEf5Z2Gh+aAq48UoapcxHsqZh9UQBqt7e3M81gDpZT0jQi2WbajSOaOU0m
            ccyZm/1njqjtWy9HKXKECYYD322ghzETTIWZX4YnWjIbxe1wh1bo9ZSfxkjEAy/0
            =1YvS
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password|client_secret)$
    version: 3.11.0
